USE [master]
GO

/****** Object:  Database [ProductmanagmentDB]    Script Date: 07-01-2021 7.11.26 PM ******/
DROP DATABASE [ProductmanagmentDB]
GO

/****** Object:  Database [ProductmanagmentDB]    Script Date: 07-01-2021 7.11.26 PM ******/
CREATE DATABASE [ProductmanagmentDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProductmanagmentDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ProductmanagmentDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProductmanagmentDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ProductmanagmentDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProductmanagmentDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProductmanagmentDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProductmanagmentDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProductmanagmentDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProductmanagmentDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProductmanagmentDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProductmanagmentDB] SET  MULTI_USER 
GO

ALTER DATABASE [ProductmanagmentDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProductmanagmentDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProductmanagmentDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProductmanagmentDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProductmanagmentDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProductmanagmentDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ProductmanagmentDB] SET  READ_WRITE 
GO


